version: "3.8"

services:
  backend:
    # build: ./
    image: node:lts-alpine
    user: root
    working_dir: /app
    volumes:
      - ./lss-client-v1:/app
    command: "sh -c 'npm install && npm run dev'"
    expose:
      - 5173
    ports:
      - "3000:5173"
    environment:
      - HOME=/app
