import { useState } from "react";

//Take in response as an object
//Display survey responses

function ResponseView() {
	const [count, setCount] = useState(0);

	//this object will be passed through the props and will be generated by looping through the responses
	const exampleResponse: {
		question1: string;
		response1: string;
		question2: string;
		response2: string;
		question3: string;
		response3: string;
	} = {
		question1:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
		response1: "xercitation ullamco laboris nisi ut aliquip",
		question2:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
		response2: "xercitation ullamco laboris nisi ut aliquip",
		question3: "commodo consequat. Duis aute irure dolor in reprehenderit in",
		response3: "qui officia deserunt mollit anim id est",
	};
	//These data points would also be passed in the props
	const exampleUser = "testUser";
	const exampleDate = "09/26/22";

	const responsesToArray = (responseObject: object) => {
		type ObjectKey = keyof typeof responseObject;
		const responseArray: any = [];
		for (const prop in responseObject) {
			const value = prop as ObjectKey;
			responseArray.push(responseObject[value]);
		}
		return responseArray;
	};

	const responseArray = responsesToArray(exampleResponse);

	return (
		<>
			<h1>
				{exampleUser}'s {exampleDate} Survey Response
			</h1>
			<ul>
				{responseArray.map((value: any) => {
					return <li key={value}>{value}</li>;
				})}
			</ul>
		</>
	);
}

export default ResponseView;
